// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjryWBpflShgCCdLCO5r-gmcwtlYMbcs0',
    appId: '1:391736139833:android:1b7a799dd7c24e0310ede8',
    messagingSenderId: '391736139833',
    projectId: 'integr-it-app-251d4',
    storageBucket: 'integr-it-app-251d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6H-cQ5JwAmz8AD8BpWCgltaUdPUUhZ6k',
    appId: '1:391736139833:ios:8967ed570cc50fe510ede8',
    messagingSenderId: '391736139833',
    projectId: 'integr-it-app-251d4',
    storageBucket: 'integr-it-app-251d4.firebasestorage.app',
    iosBundleId: 'com.example.authDemo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqD5G3Jgvrr9NzlFGIz0h_zQw4jhe5GjI',
    appId: '1:391736139833:web:b28c34adb0c25d0610ede8',
    messagingSenderId: '391736139833',
    projectId: 'integr-it-app-251d4',
    authDomain: 'integr-it-app-251d4.firebaseapp.com',
    storageBucket: 'integr-it-app-251d4.firebasestorage.app',
    measurementId: 'G-CEDSSNGCF4',
  );

}