name: iOS-ipa-build

on: 
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - name: Verify checkout and structure
        run: |
          echo "=== Current Directory ==="
          pwd
          echo ""
          echo "=== Files in root ==="
          ls -la
          echo ""
          echo "=== Check for pubspec.yaml ==="
          if [ -f "pubspec.yaml" ]; then
            echo "✅ pubspec.yaml EXISTS"
            cat pubspec.yaml | head -20
          else
            echo "❌ pubspec.yaml NOT FOUND"
            find . -name "pubspec.yaml"
          fi
      
      - name: Flutter doctor
        run: flutter doctor -v
      
      - name: Clean Flutter
        run: flutter clean
      
      - name: Get dependencies
        run: |
          flutter pub get
          flutter pub get --verbose
      
      - name: Install iOS dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..
      
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign
      
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r -9 FlutterIpaExport.ipa Payload
          ls -lh FlutterIpaExport.ipa
      
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/iphoneos/FlutterIpaExport.ipa
      
      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "iOS IPA Build"
