name: iOS-ipa-build

on: 
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install && cd ..
      
      - name: Build IPA
        run: flutter build ipa --release --no-codesign --export-options-plist=ios/ExportOptions.plist
      
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/ipa/*.ipa
